camunda:
  client:
    mode: self-managed
#    tenant-ids:
#      - <default>
#    auth:
#      client-id: <your client id>
#      client-secret: <your client secret>
#      issuer: http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/token
    zeebe:
      enabled: true
      grpc-address: http://localhost:26500
#      rest-address: http://localhost:8080
      prefer-rest-over-grpc: false
#      audience: zeebe-api